/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database.routes;

import database.commons.DBVerticle;
import database.commons.ErrorCodes;
import database.commons.GenericQuery;
import io.vertx.core.eventbus.Message;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.sql.SQLConnection;
import io.vertx.ext.sql.SQLOptions;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import service.commons.Constants;
import utils.UtilsDate;
import utils.UtilsMoney;

import static database.routes.ConfigTicketPriceDBV.CREATED_BY;
import static service.commons.Constants.ID;

/**
 *
 * @author Ulises Beltrán Gómez - beltrangomezulises@gmail.com
 */
public class SpecialTicketDBV extends DBVerticle {

    public static final String UPDATEV2 = "conektaDBV.updateV2";

    public static final String FORCE_DEFAULT = "force_default";
    public static final String IS_DEFAULT = "is_default";
    public static final String HAS_DISCOUNT = "has_discount";
    public static final String TOTAL_DISCOUNT = "total_discount";
    public static final String HAS_PREFERENT_ZONE = "has_preferent_zone";
    public static final String SPECIAL_TICKET_ID = "special_ticket_id";

    @Override
    public String getTableName() {
        return "special_ticket";
    }

    @Override
    protected void onMessage(Message<JsonObject> message) {
        super.onMessage(message);
        String action = message.headers().get(Constants.ACTION);
        switch (action) {
            case UPDATEV2:
                this.update(message);
                break;
        }
    }

    /**
     * Execute the query "create" generated by the properties of the object in the message
     *
     * @param message message from the event bus
     */
    @Override
    protected void create(Message<JsonObject> message) {
        JsonObject body = message.body();
        this.startTransaction(message, conn -> {
            Boolean isDefault = body.getBoolean(IS_DEFAULT);
            Boolean forceDefault = (Boolean) body.remove(FORCE_DEFAULT);

            if (isDefault){
                this.validateExistsDefault(null).whenComplete((exists, error) -> {
                    try {
                        if (error != null){
                            throw error;
                        }
                        if (exists){
                            if (!forceDefault){
                                throw new Exception("Default special ticket already exists");
                            }
                            this.setAllDefaultFalse(conn).whenComplete((resultSetAllDefaultFalse, errorSetAllDefaultFalse) -> {
                                try {
                                    if (errorSetAllDefaultFalse != null){
                                        throw errorSetAllDefaultFalse;
                                    }
                                    this.register(conn, message, body);
                                } catch (Throwable t){
                                    t.printStackTrace();
                                    this.rollback(conn, t, message);
                                }
                            });
                        } else {
                            this.register(conn, message, body);
                        }
                    } catch (Throwable t){
                        t.printStackTrace();
                        this.rollback(conn, t, message);
                    }
                });
            } else {
                this.register(conn, message, body);
            }
        });
    }

    /**
     * Special ticket register after validations
     * @param con
     * @param message
     * @param body
     */
    private void register(SQLConnection con, Message<JsonObject> message, JsonObject body){
        GenericQuery model = this.generateGenericCreate(body);
        con.setOptions(new SQLOptions().setAutoGeneratedKeys(true));
        con.updateWithParams(model.getQuery(), model.getParams(), reply -> {
            try{
                if(reply.failed()) {
                    throw new Exception(reply.cause());
                }
                con.query(GET_ALL_DESTINATIONID, resultHandler -> {
                    try{
                        if(reply.failed()) {
                            throw new Exception(reply.cause());
                        }
                        List<JsonObject> list = resultHandler.result().getRows();
                        List<CompletableFuture<Boolean>> pTasks = new ArrayList<>();
                        JsonArray destinations = new JsonArray();
                        int special_ticket_id = reply.result().getKeys().getInteger(0);

                        if (list.isEmpty()) {
                            JsonObject res = new JsonObject();
                            res.put("id", reply.result().getKeys().getInteger(0))
                                    .put("destinations", destinations);
                            this.commit(con, message, res);
                        } else {

                            for (JsonObject l : list) {
                                //falta get hasdiscount del body del insert principal
                                Double amount = l.getDouble("amount_base");
                                Double discount = 0.00;

                                if (body.getBoolean("has_discount") != null && body.getBoolean("has_discount")) {
                                    discount = UtilsMoney.round(amount * (body.getDouble("total_discount") / 100), 2);
                                }

                                Double total_amount = UtilsMoney.round(amount - discount, 2);
                                //int created_by = 0;
                                int config_destination_id = l.getInteger("config_destination_id");

                                JsonObject params = new JsonObject();
                                params.put("special_ticket_id", special_ticket_id);
                                params.put("amount", amount);
                                params.put("discount", discount);
                                params.put("total_amount", total_amount);
                                params.put("created_by", body.getInteger("created_by"));
                                params.put("config_destination_id", config_destination_id);

                                if (l.getInteger("from_id") != null) {
                                    JsonObject destination = new JsonObject();
                                    destination.put("route", l.getString("route"));
                                    destination.put("origin", l.getString("origin"));
                                    destination.put("destiny", l.getString("destiny"));
                                    destination.put("amount", amount);
                                    destination.put("discount", discount);
                                    destination.put("total_amount", total_amount);
                                    destinations.add(destination);
                                }

                                pTasks.add(executeInserts(con, params));
                            }
                            CompletableFuture<Void> allUpdates = CompletableFuture.allOf(pTasks.toArray(new CompletableFuture[list.size()]));
                            allUpdates.whenComplete((ps, pt) -> {
                                if (pt != null) {
                                    reportQueryError(message, pt);
                                } else {
                                    JsonObject res = new JsonObject();
                                    res.put("id", reply.result().getKeys().getInteger(0))
                                            .put("destinations", destinations);
                                    this.commit(con, message, res);
                                    //message.reply(new JsonObject().put("id", reply.result().getKeys().getInteger(0)));
                                }
                            });
                        }
                    }catch (Exception ex) {
                        ex.printStackTrace();
                        this.rollback(con, new Throwable("not insert"), message);
                    }
                });
            }catch (Exception ex) {
                ex.printStackTrace();
                reportQueryError(message, reply.cause());
            }
        });
    }

    /**
     * Validator if exists some default special ticket
     * @param specialTicketId
     * @return flag exists
     */
    private CompletableFuture<Boolean> validateExistsDefault(Integer specialTicketId){
        CompletableFuture<Boolean> future = new CompletableFuture<>();
        String QUERY = "SELECT id FROM special_ticket WHERE is_default = 1 ";
        JsonArray params = new JsonArray();
        if (specialTicketId != null){
            QUERY = QUERY.concat(" AND id != ?");
            params.add(specialTicketId);
        }
        this.dbClient.queryWithParams(QUERY, params, reply -> {
            try {
                if (reply.failed()){
                    throw reply.cause();
                }
                List<JsonObject> results = reply.result().getRows();
                Boolean result = true;
                if (results.isEmpty()){
                    result = false;
                }
                future.complete(result);
            } catch (Throwable t){
                future.completeExceptionally(t);
            }
        });
        return future;
    }

    /**
     * Update is_default false to all special ticket
     * @return flag exists
     */
    private CompletableFuture<Boolean> setAllDefaultFalse(SQLConnection conn){
        CompletableFuture<Boolean> future = new CompletableFuture<>();
        conn.update("UPDATE special_ticket SET is_default = 0", reply -> {
            try {
                if (reply.failed()){
                    throw reply.cause();
                }
                future.complete(reply.succeeded());
            } catch (Throwable t){
                future.completeExceptionally(t);
            }
        });
        return future;
    }

    private CompletableFuture<Boolean> executeInserts(SQLConnection conn, JsonObject params) {
        CompletableFuture<Boolean> future = new CompletableFuture<>();

        String gQuery = this.generateGenericCreate("config_ticket_price", params);
        gQuery += " ON DUPLICATE KEY UPDATE " +
                "amount = " + params.getDouble("amount")+ ", " +
                "discount = " + params.getDouble("discount") + ", " +
                "total_amount = " + params.getDouble("total_amount") + ", " +
                "updated_by = " + params.getInteger(CREATED_BY) + ", " +
                "updated_at = '" + UtilsDate.sdfDataBase(new Date()) + "'";
        System.out.println(gQuery);
        conn.query(gQuery, resultHandler -> {
            try{
                if(resultHandler.failed()) {
                    throw new Exception(resultHandler.cause());
                }
                future.complete(resultHandler.succeeded());
            }catch (Exception ex) {
                ex.printStackTrace();
                future.completeExceptionally(resultHandler.cause());
            }
        });
        return future;
    }

    @Override
    protected void update(Message<JsonObject> message) {
        this.startTransaction(message, (SQLConnection conn) -> {
            JsonObject body = message.body();

            Boolean isDefault = body.getBoolean(IS_DEFAULT);
            Boolean forceDefault = (Boolean) body.remove(FORCE_DEFAULT);
            Integer specialTicketId = body.getInteger(ID);

            if (isDefault){
                this.validateExistsDefault(specialTicketId).whenComplete((exists, error) -> {
                    try {
                        if (error != null){
                            throw error;
                        }
                        if (exists){
                            if (!forceDefault){
                                throw new Exception("Default special ticket already exists");
                            }
                            this.setAllDefaultFalse(conn).whenComplete((resultSetAllDefaultFalse, errorSetAllDefaultFalse) -> {
                                try {
                                    if (errorSetAllDefaultFalse != null){
                                        throw errorSetAllDefaultFalse;
                                    }
                                    body
                                        .put(TOTAL_DISCOUNT, 0.00)
                                        .put(HAS_DISCOUNT, 0);
                                    this.executeUpdate(conn, message, body);
                                } catch (Throwable t){
                                    t.printStackTrace();
                                    this.rollback(conn, t, message);
                                }
                            });
                        } else {
                            body
                                .put(TOTAL_DISCOUNT, 0.00)
                                .put(HAS_DISCOUNT, 0);
                            this.executeUpdate(conn, message, body);
                        }
                    } catch (Throwable t){
                        t.printStackTrace();
                        this.rollback(conn, t, message);
                    }
                });
            } else {
                this.executeUpdate(conn, message, body);
            }
        });
    }

    /**
     * Special ticket updater after validations
     * @param conn
     * @param message
     * @param body
     */
    private void executeUpdate(SQLConnection conn, Message<JsonObject> message, JsonObject body){
        JsonArray destinations = new JsonArray();
        String query = "select status from " + this.getTableName() + " where id = ?";
        JsonArray params = new JsonArray().add(body.getInteger("id"));
        conn.queryWithParams(query, params, reply -> {
            try{
                if(reply.failed()) {
                    throw new Exception(reply.cause());
                }
                if (reply.result().getNumRows() > 0) {
                    int status = reply.result().getRows().get(0).getInteger("status");
                    if (status == 3) {
                        this.rollback(conn, new Exception(ErrorCodes.DB_ERROR.toString() + ": can't update deleted element"), message);
                    } else {
                        if (status == 0 && body.getInteger("status") != 1) {
                            this.rollback(conn, new Exception(ErrorCodes.DB_ERROR.toString() + ": status can only change to active"), message);
                        } else {
                            GenericQuery gc = this.generateGenericUpdate(this.getTableName(), body);
                            executeUpdate(conn, gc, body.getInteger("id"), body.getInteger("updated_by"), destinations).whenComplete((Boolean updateData, Throwable error) -> {
                                if (error != null) {
                                    this.rollback(conn, error, message);
                                } else {
                                    if (updateData) {
                                        JsonObject finalResult = new JsonObject();
                                        finalResult.put("id", body.getInteger("id"))
                                                .put("destinations", destinations);
                                        this.commit(conn, message, finalResult);
                                    } else {
                                        this.rollback(conn, new Throwable("not updated"), message);
                                    }
                                }
                            });
                        }
                    }
                } else {
                    this.rollback(conn, new Exception("Element not found"), message);
                }

            }catch (Exception ex) {
                ex.printStackTrace();
                this.rollback(conn, reply.cause(), message);
            }
        });
    }

    private CompletableFuture<Boolean> executeUpdate(SQLConnection conn, GenericQuery gc, int id, int updated_by, JsonArray destinations) {
        CompletableFuture<Boolean> future = new CompletableFuture<>();
        conn.updateWithParams(gc.getQuery(), gc.getParams(), reply -> {
            try{
                if(reply.failed()){
                    throw  new Exception(reply.cause());
                }
                JsonArray params = new JsonArray().add(id).add(id);
                //System.out.println(QUERY_GET_CONFIG_PRICE);
                conn.queryWithParams(QUERY_GET_CONFIG_PRICE, params, replyGet -> {
                    try{
                        if(reply.failed()) {
                            throw new Exception(reply.cause());
                        }
                        if (replyGet.result().getNumRows() > 0) {
                            List<JsonObject> result = replyGet.result().getRows();

                            List<CompletableFuture<Boolean>> pTasks = new ArrayList<>();

                            for (JsonObject res : result) {
                                //int config_ticket_price_id = res.getInteger("id");
                                Double amount = res.getDouble("amount_base");
                                Double discount = (res.getDouble("discount") != null ? res.getDouble("discount") : 0.0);

                                int config_destination_id = res.getInteger("config_destination_id");

                                if (res.getBoolean("has_discount")) {
                                    discount = UtilsMoney.round(amount * (Double.parseDouble(res.getInteger("total_discount").toString()) / 100), 2);
                                }

                                Double total_amount = UtilsMoney.round(amount - discount, 2);
                                //System.out.println(amount + " " + discount + " " + total_amount);
                                if (res.getInteger("id") != null) {
                                    JsonArray paramsQ = new JsonArray();

                                    paramsQ.add(amount);
                                    paramsQ.add(discount);
                                    paramsQ.add(total_amount);
                                    paramsQ.add(res.getInteger("status"));
                                    paramsQ.add(updated_by);
                                    paramsQ.add(res.getInteger("id"));

                                    pTasks.add(executeQuery(conn, paramsQ));
                                } else {
                                    JsonObject paramsI = new JsonObject();
                                    paramsI.put("special_ticket_id", id);
                                    paramsI.put("amount", amount);
                                    paramsI.put("discount", discount);
                                    paramsI.put("total_amount", total_amount);
                                    paramsI.put("status", res.getInteger("status"));
                                    paramsI.put("created_by", updated_by);
                                    paramsI.put("config_destination_id", config_destination_id);

                                    pTasks.add(executeInserts(conn, paramsI));
                                }

                                if (res.getInteger("from_id") != null) {
                                    JsonObject destination = new JsonObject();
                                    destination.put("route", res.getString("route"));
                                    destination.put("origin", res.getString("origin"));
                                    destination.put("destiny", res.getString("destiny"));
                                    destination.put("amount", amount);
                                    destination.put("discount", discount);
                                    destination.put("total_amount", total_amount);
                                    destinations.add(destination);
                                }
                            }
                            CompletableFuture<Void> allUpdates = CompletableFuture.allOf(pTasks.toArray(new CompletableFuture[result.size()]));
                            allUpdates.whenComplete((ps, pt) -> {
                                if (pt != null) {
                                    future.completeExceptionally(pt.getCause());
                                } else {
                                    future.complete(true);
                                }
                            });
                        } else {
                            future.complete(reply.succeeded());
                        }
                    }catch (Exception ex) {
                        ex.printStackTrace();
                        future.completeExceptionally(replyGet.cause());
                    }
                });

            }catch(Exception e){
                future.completeExceptionally(reply.cause());
            }
        });
        return future;
    }

    private CompletableFuture<Boolean> executeQuery(SQLConnection conn, JsonArray paramsQ) {
        CompletableFuture<Boolean> future = new CompletableFuture<>();
        //System.out.println(QUERY_PRICE);
        conn.updateWithParams(QUERY_PRICE, paramsQ, resultQ -> {
            try {
                if (resultQ.succeeded()) {
                    if (resultQ.result().getUpdated() == 0) { //does not exist element with id
                        future.completeExceptionally(new Throwable("Element not found"));
                    } else {
                        future.complete(resultQ.succeeded());
                    }
                } else {
                    future.completeExceptionally(resultQ.cause());
                }
            } catch (Exception e) {
                future.completeExceptionally(e.getCause());
            }
        });
        return future;
    }

    private static final String GET_ALL_DESTINATIONID = "SELECT DISTINCT(ctp.config_destination_id), cr.name AS route, cr.from_id, bo.prefix AS origin, " +
            " bd.prefix AS destiny, ctp.amount as 'amount_base', st.base  " +
            " FROM config_ticket_price AS ctp " +
            " INNER JOIN special_ticket AS st on ctp.special_ticket_id = st.id " +
            " INNER JOIN config_destination AS cd on ctp.config_destination_id = cd.id  \n" +
            " INNER JOIN branchoffice AS bo ON cd.terminal_origin_id = bo.id " +
            " INNER JOIN branchoffice AS bd ON cd.terminal_destiny_id = bd.id " +
            " INNER JOIN config_route AS cr on cd.config_route_id = cr.id " +
            " where st.base = 1 and ctp.status = 1;";

    private static final String QUERY_GET_CONFIG_PRICE = "SELECT ctp.config_destination_id, cr.name AS route, cr.from_id, bo.prefix AS origin, bd.prefix AS destiny, " +
            " ctp.amount as 'amount_base',  ctp_st.id, ctp_st.amount, ctp_st.discount, ctp_st.total_amount, ctp_st.special_ticket_id, st2.status, st2.has_discount, st2.total_discount\n" +
            " FROM config_ticket_price AS ctp\n" +
            " LEFT JOIN special_ticket AS st on ctp.special_ticket_id = st.id\n" +
            " LEFT JOIN config_destination AS cd on ctp.config_destination_id = cd.id \n" +
            " LEFT JOIN branchoffice AS bo ON cd.terminal_origin_id = bo.id\n" +
            " LEFT JOIN branchoffice AS bd ON cd.terminal_destiny_id = bd.id\n" +
            " LEFT JOIN config_route AS cr on cd.config_route_id = cr.id\n" +
            " LEFT JOIN config_ticket_price AS ctp_st on (ctp.config_destination_id = ctp_st.config_destination_id and ctp_st.special_ticket_id = ?)\n" +
            " LEFT JOIN special_ticket AS st2 on st2.id = ? \n" +
            " where st.base = 1;";

    private static final String QUERY_PRICE = "UPDATE `config_ticket_price` " +
            "SET " +
            "`amount` = ? , " +
            "`discount` = ? , " +
            "`total_amount` = ? , " +
            "`status` = ? , " +
            "`updated_at` = CURRENT_TIMESTAMP, " +
            "`updated_by` = ? " +
            "WHERE id= ? ";

}