-- 1543081004 UP Add-customer-addresses
CREATE TABLE `customer_addresses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `address` varchar(255) NOT NULL,
  `street_id` int(11) NOT NULL,
  `no_ext` int(11) NOT NULL,
  `no_int` varchar(15) DEFAULT NULL,
  `suburb_id` int(11) DEFAULT NULL,
  `city_id` int(11) NOT NULL,
  `state_id` int(11) NOT NULL,
  `country_id` int(11) NOT NULL,
  `reference` text,
  `zip_code` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '1',
  `updated_at` datetime DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `customer_addresses_customer_id_idx` (`customer_id`),
  KEY `customer_addresses_street_id_idx` (`street_id`),
  KEY `customer_addresses_city_id_idx` (`city_id`),
  KEY `customer_addresses_state_id_idx` (`state_id`),
  KEY `customer_addresses_country_id_idx` (`country_id`),
  KEY `customer_addresses_created_by_idx` (`created_by`),
  CONSTRAINT `customer_addresses_city_id` FOREIGN KEY (`city_id`) REFERENCES `city` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `customer_addresses_country_id` FOREIGN KEY (`country_id`) REFERENCES `country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `customer_addresses_created_by` FOREIGN KEY (`created_by`) REFERENCES `employee` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `customer_addresses_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `customer_addresses_state_id` FOREIGN KEY (`state_id`) REFERENCES `state` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `customer_addresses_street_id` FOREIGN KEY (`street_id`) REFERENCES `street` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;