-- 1558120288 UP create-table-subscriptions
CREATE TABLE subscriptions (
id INT(11) NOT NULL AUTO_INCREMENT,
email VARCHAR(50) UNIQUE NOT NULL,
status INT(11) NOT NULL DEFAULT 1,
created_by INT(11) NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_by INT(11) DEFAULT NULL,
updated_at DATETIME DEFAULT NULL,
PRIMARY KEY(id),
INDEX(email)
)ENGINE=InnoDB CHARSET=utf8;