-- 1560325933 UP create table promos
CREATE TABLE IF NOT EXISTS promos(
  id int(11) NOT NULL AUTO_INCREMENT,
  discount_code VARCHAR(50) NOT NULL UNIQUE,
  name varchar(25) NOT NULL,
  description text DEFAULT NULL,
  service enum('boardingpass', 'parcel', 'rental') NOT NULL,
  discount_type enum('direct_amount', 'direct_percent', 'free_n_product', 'discount_n_product') NOT NULL,
  discount decimal(12,2) NOT NULL DEFAULT 0.00,
  num_products int(11) DEFAULT NULL,
  rule enum('boardingpass_abierto', 'boardingpass_redondo') DEFAULT NULL,
  usage_limit int(11) NOT NULL DEFAULT 0,
  used int(11) NOT NULL DEFAULT 0,
  available_days varchar(3) NOT NULL DEFAULT 'all',
  apply_to_special_tickets varchar(30) DEFAULT NULL,
  has_specific_customer tinyint(1) DEFAULT 0,
  since date NOT NULL,
  until date NOT NULL,
  status int(11) NOT NULL DEFAULT 1,
  created_at datetime NULL DEFAULT CURRENT_TIMESTAMP,
  created_by int(11) NOT NULL,
  updated_at datetime DEFAULT NULL,
  updated_by int(11) DEFAULT NULL,
  PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;