-- 1566834421 UP create-table-luggages
CREATE TABLE luggages (
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
height DECIMAL(12,2) NOT NULL,
width DECIMAL(12, 2) NOT NULL,
length DECIMAL(12, 2) NOT NULL,
weight DECIMAL(12, 2) NOT NULL,
status INT(11) NOT NULL DEFAULT 1,
created_by INT(11) NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_by INT(11) DEFAULT NULL,
updated_at DATETIME DEFAULT NULL,
PRIMARY KEY(id)
)ENGINE=InnoDB CHARSET=utf8;