-- 1575316206 UP added-contpaq-tables
CREATE TABLE IF NOT EXISTS `CONTPAQ_ClientesProvedores`
(
    `id`                                  int(11)     NOT NULL AUTO_INCREMENT,
    `cCodigoCliente`                      varchar(31) NOT NULL,
    `cRazonSocial`                        varchar(61)          DEFAULT NULL,
    `cFechaAlta`                          datetime    NOT NULL,
    `cRFC`                                varchar(21)          DEFAULT NULL,
    `cCURP`                               varchar(21)          DEFAULT NULL,
    `cDenComercial`                       varchar(51)          DEFAULT NULL,
    `cRepLegal`                           varchar(51)          DEFAULT NULL,
    `cNombreMoneda`                       varchar(61)          DEFAULT NULL,
    `cListaPreciosCliente`                int(11)              DEFAULT '0',
    `cDescuentoMovto`                     double               DEFAULT NULL,
    `cBanVentaCredito`                    int(11)              DEFAULT NULL,
    `cCodigoValorClasificacionCliente1`   varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionCliente2`   varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionCliente3`   varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionCliente4`   varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionCliente5`   varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionCliente6`   varchar(4)           DEFAULT NULL,
    `cTipoCliente`                        int(11)     NOT NULL,
    `cEstatus`                            smallint(6) NOT NULL DEFAULT '1',
    `cFechaBaja`                          datetime    NOT NULL,
    `cFechaUltimaRevision`                datetime    NOT NULL,
    `cLimiteCreditoCliente`               double               DEFAULT NULL,
    `cDiasCreditoCliente`                 int(11)              DEFAULT NULL,
    `cBanExcederCredito`                  smallint(6)          DEFAULT NULL,
    `cDescuentoProntoPago`                double               DEFAULT NULL,
    `cDiasProntoPago`                     int(11)              DEFAULT NULL,
    `cInteresMoratorio`                   double               DEFAULT NULL,
    `cDiaPago`                            int(11)              DEFAULT NULL,
    `cDiasRevision`                       int(11)              DEFAULT NULL,
    `cMensajeria`                         varchar(21)          DEFAULT NULL,
    `cCuentaMensajeria`                   varchar(61)          DEFAULT NULL,
    `cDiasEmbarqueCliente`                int(11)              DEFAULT NULL,
    `cCodigoAlmacen`                      varchar(31)          DEFAULT NULL,
    `cCodigoAgenteVenta`                  varchar(31)          DEFAULT NULL,
    `cCodigoAgenteCobro`                  varchar(31)          DEFAULT NULL,
    `cRestriccionAgente`                  int(11)              DEFAULT NULL,
    `cImpuesto1`                          double               DEFAULT NULL,
    `cImpuesto2`                          double               DEFAULT NULL,
    `cImpuesto3`                          double               DEFAULT NULL,
    `cRetencionCliente1`                  double               DEFAULT NULL,
    `cRetencionCliente2`                  double               DEFAULT NULL,
    `cCodigoValorClasificacionProveedor1` varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionProveedor2` varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionProveedor3` varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionProveedor4` varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionProveedor5` varchar(4)           DEFAULT NULL,
    `cCodigoValorClasificacionProveedor6` varchar(4)           DEFAULT NULL,
    `cLimiteCreditoProveedor`             double               DEFAULT NULL,
    `cDiasCreditoProveedor`               int(11)              DEFAULT NULL,
    `cTiempoEntrega`                      int(11)              DEFAULT NULL,
    `cDiasEmbarqueProveedor`              int(11)              DEFAULT NULL,
    `cImpuestoProveedor1`                 double               DEFAULT NULL,
    `cImpuestoProveedor2`                 double               DEFAULT NULL,
    `cImpuestoProveedor3`                 double               DEFAULT NULL,
    `cRetencionProveedor1`                double               DEFAULT NULL,
    `cRetencionProveedor2`                double               DEFAULT NULL,
    `cBanInteresMoratorio`                smallint(6)          DEFAULT NULL,
    `cTextoExtra1`                        varchar(51)          DEFAULT NULL,
    `cTextoExtra2`                        varchar(51)          DEFAULT NULL,
    `cTextoExtra3`                        varchar(51)          DEFAULT NULL,
    `cFechaExtra`                         datetime    NOT NULL,
    `cImporteExtra1`                      double               DEFAULT NULL,
    `cImporteExtra2`                      double               DEFAULT NULL,
    `cImporteExtra3`                      double               DEFAULT NULL,
    `cImporteExtra4`                      double               DEFAULT NULL,
    `estatusServicio`                     smallint(6)          DEFAULT '0',
    `tipoPeticion`                        varchar(10)          DEFAULT NULL,
    `idUsuario`                           int(11)     NOT NULL DEFAULT '0',
    `cTipoCatalogo`                       int(11)              DEFAULT NULL,
    `cTipoDireccion`                      int(11)              DEFAULT NULL,
    `cCodigoPostal`                       varchar(8)           DEFAULT NULL,
    `cPais`                               varchar(45)          DEFAULT NULL,
    `cEstado`                             varchar(45)          DEFAULT NULL,
    `cCiudad`                             varchar(45)          DEFAULT NULL,
    `cColonia`                            varchar(60)          DEFAULT NULL,
    `cNombreCalle`                        varchar(100)         DEFAULT NULL,
    `cNumeroExterior`                     varchar(10)          DEFAULT NULL,
    `cNumeroInterior`                     varchar(10)          DEFAULT NULL,
    `cDireccionWeb`                       varchar(100)         DEFAULT NULL,
    `cEmail`                              varchar(50)          DEFAULT NULL,
    `cTelefono1`                          varchar(15)          DEFAULT NULL,
    `cTelefono2`                          varchar(15)          DEFAULT NULL,
    `cTelefono3`                          varchar(15)          DEFAULT NULL,
    `cTelefono4`                          varchar(15)          DEFAULT NULL,
    `cTextoExtra`                         varchar(45)          DEFAULT NULL,
    `CMETODOPAG`                          varchar(5)           DEFAULT NULL,
    `CBANCFD`                             varchar(5)           DEFAULT NULL,
    `CUSOCFDI`                            varchar(5)           DEFAULT NULL,
    `empresa`                             int(11)              DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `index1` (`cCodigoCliente`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS `CONTPAQ_Documentos`
(
    `id`               int(11)     NOT NULL AUTO_INCREMENT,
    `aFolio`           double               DEFAULT NULL,
    `aNumMoneda`       int(11)              DEFAULT NULL,
    `aTipoCambio`      double               DEFAULT NULL,
    `aImporte`         double               DEFAULT NULL,
    `aDescuentoDoc1`   double               DEFAULT NULL,
    `aDescuentoDoc2`   double               DEFAULT NULL,
    `aSistemaOrigen`   int(11)              DEFAULT NULL,
    `aCodConcepto`     varchar(31)          DEFAULT NULL,
    `aSerie`           varchar(31)          DEFAULT NULL,
    `aFecha`           datetime    NOT NULL,
    `aCodigoCteProv`   varchar(31)          DEFAULT NULL,
    `aCodigoAgente`    varchar(31)          DEFAULT NULL,
    `aReferencia`      varchar(21)          DEFAULT NULL,
    `aAfecta`          int(11)              DEFAULT NULL,
    `aGasto1`          double               DEFAULT NULL,
    `aGasto2`          double               DEFAULT NULL,
    `aGasto3`          double               DEFAULT NULL,
    `tipoPeticion`     varchar(7)           DEFAULT NULL,
    `estatusServicio`  smallint(6) NOT NULL,
    `idUsuario`        int(11)     NOT NULL DEFAULT '0',
    `CMETODOPAG`       varchar(5)           DEFAULT NULL,
    `CBANCFD`          varchar(5)           DEFAULT NULL,
    `CUSOCFDI`         varchar(5)           DEFAULT NULL,
    `cLugarExpedicion` varchar(5)           DEFAULT NULL,
    `empresa`          int(11)              DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS `CONTPAQ_Movimientos`
(
    `id`                int(11) NOT NULL AUTO_INCREMENT,
    `idDocumento`       int(11)     DEFAULT NULL,
    `aConsecutivo`      int(11)     DEFAULT NULL,
    `aUnidades`         double      DEFAULT NULL,
    `aImporte`          double      DEFAULT NULL,
    `aPrecio`           double      DEFAULT NULL,
    `aCosto`            double      DEFAULT NULL,
    `aCodProdSer`       varchar(31) DEFAULT NULL,
    `aCodAlmacen`       varchar(31) DEFAULT NULL,
    `aReferencia`       varchar(21) DEFAULT NULL,
    `aCodClasificacion` varchar(31) DEFAULT NULL,
    `tipoPeticion`      varchar(7)  DEFAULT NULL,
    `estatusServicio`   smallint(6) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idxIdDocumento` (`idDocumento`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE IF NOT EXISTS `CONTPAQ_Productos`
(
    `id`                         int(11)    NOT NULL AUTO_INCREMENT,
    `cCodigoProducto`            varchar(31)         DEFAULT NULL,
    `cNombreProducto`            varchar(61)         DEFAULT NULL,
    `cDescripcionProducto`       varchar(61)         DEFAULT NULL,
    `cTipoProducto`              int(11)             DEFAULT NULL,
    `cFechaAltaProducto`         datetime   NOT NULL,
    `cFechaBaja`                 datetime   NOT NULL,
    `cStatusProducto`            int(11)    NOT NULL DEFAULT '1',
    `cControlExistencia`         int(11)             DEFAULT NULL,
    `cMetodoCosteo`              int(11)             DEFAULT NULL,
    `cCodigoUnidadBase`          varchar(31)         DEFAULT NULL,
    `cCodigoUnidadNoConvertible` varchar(31)         DEFAULT NULL,
    `cPrecio1`                   double              DEFAULT NULL,
    `cPrecio2`                   double              DEFAULT NULL,
    `cPrecio3`                   double              DEFAULT NULL,
    `cPrecio4`                   double              DEFAULT NULL,
    `cPrecio5`                   double              DEFAULT NULL,
    `cPrecio6`                   double              DEFAULT NULL,
    `cPrecio7`                   double              DEFAULT NULL,
    `cPrecio8`                   double              DEFAULT NULL,
    `cPrecio9`                   double              DEFAULT NULL,
    `cPrecio10`                  double              DEFAULT NULL,
    `cImpuesto1`                 double              DEFAULT NULL,
    `cImpuesto2`                 double              DEFAULT NULL,
    `cImpuesto3`                 double              DEFAULT NULL,
    `cRetencion1`                double              DEFAULT NULL,
    `cRetencion2`                double              DEFAULT NULL,
    `cNombreCaracteristica1`     varchar(61)         DEFAULT NULL,
    `cNombreCaracteristica2`     varchar(61)         DEFAULT NULL,
    `cNombreCaracteristica3`     varchar(61)         DEFAULT NULL,
    `cCodigoValorClasificacion1` varchar(5)          DEFAULT NULL,
    `cCodigoValorClasificacion2` varchar(5)          DEFAULT NULL,
    `cCodigoValorClasificacion3` varchar(5)          DEFAULT NULL,
    `cCodigoValorClasificacion4` varchar(5)          DEFAULT NULL,
    `cCodigoValorClasificacion5` varchar(5)          DEFAULT NULL,
    `cCodigoValorClasificacion6` varchar(5)          DEFAULT NULL,
    `cTextoExtra1`               varchar(51)         DEFAULT NULL,
    `cTextoExtra2`               varchar(51)         DEFAULT NULL,
    `cTextoExtra3`               varchar(51)         DEFAULT NULL,
    `cFechaExtra`                datetime   NOT NULL,
    `cImporteExtra1`             double              DEFAULT NULL,
    `cImporteExtra2`             double              DEFAULT NULL,
    `cImporteExtra3`             double              DEFAULT NULL,
    `cImporteExtra4`             double              DEFAULT NULL,
    `tipoPeticion`               varchar(7) NOT NULL,
    `estatusServicio`            int(11)    NOT NULL,
    `idUsuario`                  int(11)    NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `index1` (`cCodigoProducto`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


