-- 1575316206 DOWN added-contpaq-tables
DROP TABLE IF EXISTS CONTPAQ_ClientesProvedores;
DROP TABLE IF EXISTS CONTPAQ_Movimientos;
DROP TABLE IF EXISTS CONTPAQ_Productos;
DROP TABLE IF EXISTS CONTPAQ_Documentos;