-- 1589647633 DOWN boarding-pass-passenger-indexes

DROP INDEX boarding_pass_passenger_principal_passenger_idx ON boarding_pass_passenger;
DROP INDEX boarding_pass_passenger_is_customer_idx ON boarding_pass_passenger;
DROP INDEX boarding_pass_passenger_is_child_under_age_idx ON boarding_pass_passenger;
DROP INDEX boarding_pass_passenger_status_idx ON boarding_pass_passenger;
DROP INDEX boarding_pass_passenger_created_at_idx ON boarding_pass_passenger;
