-- 1665379617 DOWN invoices-indexes
DROP INDEX boardingpass_invoice_complement_status_idx ON boardingpass_invoice_complement;
DROP INDEX boardingpass_invoice_complement_status_cfdi_idx ON boardingpass_invoice_complement;
DROP INDEX boardingpass_invoice_complement_tipo_cfdi_idx ON boardingpass_invoice_complement;
DROP INDEX boardingpass_invoice_complement_created_at_idx ON boardingpass_invoice_complement;

DROP INDEX parcel_invoice_complement_status_idx ON parcel_invoice_complement;
DROP INDEX parcel_invoice_complement_status_cfdi_idx ON parcel_invoice_complement;
DROP INDEX parcel_invoice_complement_tipo_cfdi_idx ON parcel_invoice_complement;
DROP INDEX parcel_invoice_complement_created_at_idx ON parcel_invoice_complement;

DROP INDEX guiapp_invoice_complement_status_idx ON guiapp_invoice_complement;
DROP INDEX guiapp_invoice_complement_status_cfdi_idx ON guiapp_invoice_complement;
DROP INDEX guiapp_invoice_complement_tipo_cfdi_idx ON guiapp_invoice_complement;
DROP INDEX guiapp_invoice_complement_created_at_idx ON guiapp_invoice_complement;