-- 1690034905 DOWN add-prepaid-price-km
ALTER TABLE pp_price_km
DROP COLUMN price_kg,
DROP COLUMN price_cubic,
DROP COLUMN R0,
DROP COLUMN R1,
DROP COLUMN R2,
DROP COLUMN R3,
DROP COLUMN R4,
DROP COLUMN R5,
DROP COLUMN R6,
DROP COLUMN R7;