-- 1743828421 UP create-payment-complement-table
CREATE TABLE `payment_complement` (
  `id` int NOT NULL AUTO_INCREMENT,
  `payment_date` datetime DEFAULT NULL,
  `customer_id` int DEFAULT NULL,
  `customer_billing_information_id` int DEFAULT NULL,
  `payment_id` int DEFAULT NULL,
  `payment_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `iva_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `iva_withheld_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `created_by` int NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `status` tinyint DEFAULT '1',
  `invoice_status` enum('pending','done','error') NOT NULL DEFAULT 'pending',
  `email` varchar(100) NOT NULL,
  `uuid` varchar(50) DEFAULT NULL,
  `serie` varchar(10) DEFAULT NULL,
  `folio` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `payment_complement_customer_id_idx` (`customer_id`),
  KEY `payment_complement_customer_billing_information_id_idx` (`customer_billing_information_id`),
  KEY `payment_complement_payment_id_idx` (`payment_id`),
  KEY `payment_complement_status_idx` (`status`),
  KEY `payment_complement_invoice_status_idx` (`invoice_status`),
  KEY `payment_complement_created_at_idx` (`created_at`),
  KEY `payment_complement_folio_idx` (`folio`),
  CONSTRAINT `payment_complement_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `payment_complement_customer_billing_information_id` FOREIGN KEY (`customer_billing_information_id`) REFERENCES `customer_billing_information` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `payment_complement_payment_id` FOREIGN KEY (`payment_id`) REFERENCES `payment` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
);