-- 1756577106 UP create-credit-note-table
CREATE TABLE `credit_note` (
  `id` int NOT NULL AUTO_INCREMENT,
  `issue_date` datetime DEFAULT NULL,
  `customer_id` int DEFAULT NULL,
  `customer_billing_information_id` int DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `iva_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `iva_withheld_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `created_by` int NOT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `status` tinyint DEFAULT '1',
  `invoice_status` enum('pending','done','error') NOT NULL DEFAULT 'pending',
  `email` varchar(100) NOT NULL,
  `uuid` varchar(50) DEFAULT NULL,
  `serie` varchar(10) DEFAULT NULL,
  `folio` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `credit_note_customer_id_idx` (`customer_id`),
  KEY `credit_note_customer_billing_information_id_idx` (`customer_billing_information_id`),
  KEY `credit_note_status_idx` (`status`),
  KEY `credit_note_invoice_status_idx` (`invoice_status`),
  KEY `credit_note_issue_date_idx` (`issue_date`),
  KEY `credit_note_created_at_idx` (`created_at`),
  KEY `credit_note_serie_idx` (`serie`),
  KEY `credit_note_folio_idx` (`folio`),
  CONSTRAINT `credit_note_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `credit_note_customer_billing_information_id` FOREIGN KEY (`customer_billing_information_id`) REFERENCES `customer_billing_information` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);