#!/usr/bin/env bash
set -x
set -e

{
    ENV_FILE=.env

    touch $ENV_FILE
    chmod 600 $ENV_FILE

    echo "API_MAIL_HOSTNAME=${API_MAIL_HOSTNAME}" > $ENV_FILE
    echo "API_MAIL_PORT=${API_MAIL_PORT}" >> $ENV_FILE
    echo "API_MAIL_SSL=${API_MAIL_SSL}" >> $ENV_FILE
    echo "API_MAIL_TLS=${API_MAIL_TLS}" >> $ENV_FILE
    echo "API_MAIL_USERNAME=${API_MAIL_USERNAME}" >> $ENV_FILE
    echo "API_MAIL_PASSWORD=${API_MAIL_PASSWORD}" >> $ENV_FILE
    echo "API_HTTP_SERVER_PORT=${API_HTTP_SERVER_PORT}" >> $ENV_FILE
    echo "API_DB_SERVER_URL=${API_DB_SERVER_URL}" >> $ENV_FILE
    echo "API_DB_SERVER_DRIVER=${API_DB_SERVER_DRIVER}" >> $ENV_FILE
    echo "API_AUTH_SERVER_HOST=${API_AUTH_SERVER_HOST}" >> $ENV_FILE
    echo "API_AUTH_SERVER_PORT=${API_AUTH_SERVER_PORT}" >> $ENV_FILE
    echo "API_DB_SERVER_USER=${API_DB_SERVER_USER}" >> $ENV_FILE
    echo "API_DB_SERVER_PASSWORD=${API_DB_SERVER_PASSWORD}" >> $ENV_FILE
    echo "API_DB_SERVER_MAX_POOL_SIZE=${API_DB_SERVER_MAX_POOL_SIZE}" >> $ENV_FILE
    echo "API_DB_SERVER_MIN_POOL_SIZE=${API_DB_SERVER_MIN_POOL_SIZE}" >> $ENV_FILE
    echo "API_DB_SERVER_INI_POOL_SIZE=${API_DB_SERVER_INI_POOL_SIZE}" >> $ENV_FILE
    echo "API_DB_SERVER_MAX_STATEMENTS=${API_DB_SERVER_MAX_STATEMENTS}" >> $ENV_FILE
    echo "API_DB_SERVER_MAX_STATEMENTS_PER_CONNECTION=${API_DB_SERVER_MAX_STATEMENTS_PER_CONNECTION}" >> $ENV_FILE
    echo "API_DB_SERVER_MAX_IDLE_TIME=${API_DB_SERVER_MAX_IDLE_TIME}" >> $ENV_FILE
    echo "WEB_SERVER_HOSTNAME=${WEB_SERVER_HOSTNAME}" >> $ENV_FILE
    echo "AWS_SNS_ACCESS_KEY=${AWS_SNS_ACCESS_KEY}" >> $ENV_FILE
    echo "AWS_SNS_SECRET_KEY=${AWS_SNS_SECRET_KEY}" >> $ENV_FILE
    echo "SNS_TOPIC_INVOICE=${SNS_TOPIC_INVOICE}" >> $ENV_FILE
    echo "SNS_TOPIC_CUSTOMER=${SNS_TOPIC_CUSTOMER}" >> $ENV_FILE
    echo "SELF_SERVER_HOST=${SELF_SERVER_HOST}" >> $ENV_FILE
    echo "INVOICE_SERVER_HOST=${INVOICE_SERVER_HOST}" >> $ENV_FILE
    echo "CONEKTA_API_KEY=${CONEKTA_API_KEY}" >> $ENV_FILE
    echo "MONGODB_HOST=${MONGODB_HOST}" >> $ENV_FILE
    echo "MONGODB_PORT=${MONGODB_PORT}" >> $ENV_FILE
    echo "MONGODB_NAME=${MONGODB_NAME}" >> $ENV_FILE
    echo "DOUBLE_INVOICING=${DOUBLE_INVOICING}" >> $ENV_FILE
    echo "INVOICE_FILE_HOST=${INVOICE_FILE_HOST}" >> $ENV_FILE
    echo "INVOICE_PARCEL_SERVER_HOST=${INVOICE_PARCEL_SERVER_HOST}" >> $ENV_FILE
    echo "INVOICE_PARCEL_FILE_HOST=${INVOICE_PARCEL_FILE_HOST}" >> $ENV_FILE
    echo "VALIDATE_PERIOD_INVOICE=${VALIDATE_PERIOD_INVOICE}" >> $ENV_FILE
    echo "REGISTER_INVOICES=${REGISTER_INVOICES}" >> $ENV_FILE
    echo "INVOICE_PREFIX=${INVOICE_PREFIX}" >> $ENV_FILE
    echo "CUSTOMER_INVOICE_PREFIX=${CUSTOMER_INVOICE_PREFIX}" >> $ENV_FILE
    echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}" >> $ENV_FILE
    echo "INVOICE_PARCEL_PREFIX=${INVOICE_PARCEL_PREFIX}" >> $ENV_FILE
    echo "RFC_PARCEL=${RFC_PARCEL}" >> $ENV_FILE
    echo "RFC_BOARDINGPASS=${RFC_BOARDINGPASS}" >> $ENV_FILE
    echo "RFC_NAME_PARCEL=${RFC_NAME_PARCEL}" >> $ENV_FILE
    echo "RFC_NAME_BOARDINGPASS=${RFC_NAME_BOARDINGPASS}" >> $ENV_FILE
    echo "PARCEL_DESTINATION_NAME=${PARCEL_DESTINATION_NAME}" >> $ENV_FILE
    echo "PARCEL_DESTINATION_RFC=${PARCEL_DESTINATION_RFC}" >> $ENV_FILE
    echo "TIMBOX_PWD=${TIMBOX_PWD}" >> $ENV_FILE
    echo "TIMBOX_URL=${TIMBOX_URL}" >> $ENV_FILE
    echo "BOARDINGPASS_KEYPEM_PATH=${BOARDINGPASS_KEYPEM_PATH}" >> $ENV_FILE
    echo "BRANCH_KEY=${BRANCH_KEY}" >> $ENV_FILE
    echo "FIREBASE_ADMIN_SDK_JSON=${FIREBASE_ADMIN_SDK_JSON}" >> $ENV_FILE
    echo "PARCEL_KEYPEM_PATH=${PARCEL_KEYPEM_PATH}" >> $ENV_FILE
    echo "INVOICE_INCOME_BASE=${INVOICE_INCOME_BASE}" >> $ENV_FILE
    echo "INVOICE_INCOME_PARCEL=${INVOICE_INCOME_PARCEL}" >> $ENV_FILE
    echo "INVOICE_CCP_BASE=${INVOICE_CCP_BASE}" >> $ENV_FILE
    echo "INVOICE_LAST_MILE_BASE=${INVOICE_LAST_MILE_BASE}" >> $ENV_FILE
    echo "PAYMENT_COMPLEMENT_BASE=${PAYMENT_COMPLEMENT_BASE}" >> $ENV_FILE
} &> /dev/null